//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SetID.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SETID_DIALOG                102
#define IDR_HTML_SETTYPE1               103
#define IDR_MAINFRAME                   128
#define IDD_SET_ONE                     131
#define IDD_SET_TWO                     132
#define IDD_SET_THREE                   133
#define IDD_SET_NEWTWO                  137
#define IDC_TAB1                        1001
#define IDC_BUTTON_CONNECT              1004
#define IDC_COMBO_ONE                   1005
#define IDC_BUTTON2                     1007
#define IDC_BUTTON_PORT_GETID           1007
#define IDC_BUTTON_SERVER_GETTIME       1007
#define IDC_BUTTON_TAG_SETRESPONSE      1007
#define IDC_BUTTON3                     1008
#define IDC_BUTTON_PORT_SETID           1008
#define IDC_BUTTON_SERVER_SETTIME       1008
#define IDC_BUTTON_TAG_GETPOWER         1008
#define IDC_EDIT2                       1009
#define IDC_EDIT_PORT_GETID1            1009
#define IDC_EDIT_SERVER_GETTIME         1009
#define IDC_EDIT_TAG_GETRESPONSE        1009
#define IDC_EDIT3                       1010
#define IDC_EDIT_PORT_SETID2            1010
#define IDC_EDIT_LOCAL_ID1              1010
#define IDC_EDIT_SERVER_SETTIME         1010
#define IDC_EDIT4                       1011
#define IDC_EDIT_PORT_SETID1            1011
#define IDC_EDIT_LOCAL_ID2              1011
#define IDC_EDIT_ROUTER_GETTIME         1011
#define IDC_EDIT5                       1012
#define IDC_EDIT_PORT_GETID2            1012
#define IDC_EDIT_LOCAL_SETID2           1012
#define IDC_EDIT_ROUTER_SETTIME         1012
#define IDC_BUTTON4                     1013
#define IDC_EDIT_ROUTER_SETID1          1013
#define IDC_BUTTON_SETPOWER             1013
#define IDC_BUTTON_TAG_SETPOWER         1013
#define IDC_EDIT_getId2                 1013
#define IDC_BUTTON5                     1014
#define IDC_EDIT_ROUTER_SETID2          1014
#define IDC_BUTTON_GETRESPONSE          1014
#define IDC_EDIT_getId1                 1014
#define IDC_BUTTON6                     1015
#define IDC_BUTTON_TAG_GETWORKTIME      1015
#define IDC_BUTTON_ROUTER_GETTIME       1015
#define IDC_EDIT_setId1                 1015
#define IDC_BUTTON7                     1016
#define IDC_BUTTON_TAG_SETWORKTIME      1016
#define IDC_BUTTON_ROUTER_SETTIME       1016
#define IDC_EDIT_setId2                 1016
#define IDC_BUTTON8                     1017
#define IDC_BUTTON_SETRESPONSE          1017
#define IDC_EDIT_readWifiCount          1017
#define IDC_BUTTON9                     1018
#define IDC_EDIT_checkIdTime            1018
#define IDC_EDIT6                       1019
#define IDC_EDIT_GETRESPONSE            1019
#define IDC_EDIT_TAG_GETPOWER           1019
#define IDC_EDIT_readPassWord           1019
#define IDC_EDIT_readPort               1020
#define IDC_EDIT8                       1021
#define IDC_EDIT_TAG_SETRESPONSE        1021
#define IDC_EDIT_LOCAL2_GETID2          1021
#define IDC_EDIT_setIdTime              1021
#define IDC_EDIT9                       1022
#define IDC_EDIT_LOCAL2_SETID1          1022
#define IDC_EDITsetWifiCount            1022
#define IDC_EDIT10                      1023
#define IDC_EDIT_TAG_GETWORKTIME        1023
#define IDC_EDIT_setWifiPassword        1023
#define IDC_EDIT11                      1024
#define IDC_EDIT_TAG_SETWORKTIME        1024
#define IDC_EDIT_setPort                1024
#define IDC_EDIT12                      1025
#define IDC_EDIT_LOCAL2_SETID2          1025
#define IDC_EDIT13                      1026
#define IDC_EDIT14                      1027
#define IDC_BUTTON10                    1028
#define IDC_BUTTON11                    1029
#define IDC_BUTTON12                    1030
#define IDC_BUTTON13                    1031
#define IDC_BUTTON14                    1032
#define IDC_BUTTON15                    1033
#define IDC_BUTTON16                    1034
#define IDC_BUTTON17                    1035
#define IDC_BUTTON18                    1036
#define IDC_EDIT15                      1037
#define IDC_EDIT17                      1039
#define IDC_IPADDRESS1                  1040
#define IDC_IPADDRESS2                  1041
#define IDC_IPADDRESS3                  1042
#define IDC_EDIT18                      1043
#define IDC_EDIT19                      1044
#define IDC_EDIT20                      1045
#define IDC_BUTTON19                    1046
#define IDC_IPADDRESS4                  1047
#define IDC_EDIT21                      1048
#define IDC_BUTTON20                    1049
#define IDC_IPADDRESS5                  1050
#define IDC_IPADDRESS6                  1051
#define IDC_EDIT22                      1052
#define IDC_EDIT23                      1053
#define IDC_EDIT24                      1054
#define IDC_IPADDRESS7                  1055
#define IDC_EDIT25                      1056
#define IDC_BUTTON21                    1057
#define IDC_IPADDRESS8                  1058
#define IDC_EDIT26                      1059
#define IDC_BUTTON1                     1060
#define IDC_SERVER_GETID                1060
#define IDC_BUTTON_GETPOWER             1060
#define IDC_BUTTON_TAG_GETRESPONSE      1060
#define IDC_EDIT1                       1061
#define IDC_EDIT_SERVER_GETID1          1061
#define IDC_EDIT_LOCAL_SETID1           1061
#define IDC_EDIT_GETPOWER               1061
#define IDC_TAG_GETID                   1062
#define IDC_BUTTON_getID                1062
#define IDC_TAG_SETID                   1063
#define IDC_BUTTON_GETTIME              1064
#define IDC_BUTTON_SETTIME              1065
#define IDC_BUTTON_checkDrivaceTime     1065
#define IDC_SERVER_SETID                1066
#define IDC_BUTTON_readWifiCount        1066
#define IDC_ROUTER_GETID                1067
#define IDC_BUTTON_readWifiPassword     1067
#define IDC_ROUTER_SETID                1068
#define IDC_BUTTON_readIPadress         1068
#define IDC_BUTTON_readPort             1069
#define IDC_EDIT_TAG_GETID1             1070
#define IDC_BUTTON_setID                1070
#define IDC_EDIT_TAG_GETID2             1071
#define IDC_BUTTON_setDrivaceIDTime     1071
#define IDC_EDIT_TAG_SETID1             1072
#define IDC_BUTTON_setWifiCount         1072
#define IDC_EDIT_TAG_SETID2             1073
#define IDC_BUTTON_setWifiPassword      1073
#define IDC_EDIT_TAG_GETTIME            1074
#define IDC_BUTTON_setPort              1074
#define IDC_EDIT_TAG_SETTIME            1075
#define IDC_BUTTON_setIpAdress          1075
#define IDC_EDIT_SERVER_GETID2          1076
#define IDC_EDIT_SERVER_SETID1          1077
#define IDC_EDIT_SERVER_SETID2          1078
#define IDC_EDIT_ROUTER_GETID1          1079
#define IDC_EDIT_ROUTER_GETID2          1080
#define IDC_COMBO_THREE                 1081
#define IDC_BUTTON_TAG_GETID            1082
#define IDC_BUTTON_TAG_SETID            1083
#define IDC_BUTTON_TAG_GETSLEEPTIME     1084
#define IDC_BUTTON_TAG_SETSLEEPTIME     1085
#define IDC_EDIT_TAG_GETSLEEPTIME       1087
#define IDC_EDIT_TAG_SETSLEEPTIME       1088
#define IDC_BUTTON_LOCAL_DHCP           1089
#define IDC_BUTTON_LOCAL_STATICIP       1090
#define IDC_BUTTON_LOCAL_SETIP          1091
#define IDC_BUTTON_LOCAL_SETPORT        1092
#define IDC_BUTTON_LOCAL_SETNAME        1093
#define IDC_BUTTON_LOCAL_SETTIME        1094
#define IDC_BUTTON_LOCAL_SUBMASK        1095
#define IDC_BUTTON_LOCAL_GATEWAY        1096
#define IDC_BUTTON_SERVER_DHCP          1097
#define IDC_BUTTON_SERVER_STATICIP      1098
#define IDC_BUTTON_SERVER_SETIP         1099
#define IDC_BUTTON_SERVER_SETPORT       1100
#define IDC_EDIT_LOCAL_DHCP             1101
#define IDC_IPADDRESS_LOCAL_IP          1102
#define IDC_EDIT_LOCAL_PORT             1103
#define IDC_EDIT_LOCAL_MAC              1104
#define IDC_EDIT_LOCAL_NAME             1105
#define IDC_EDIT_LOCAL_TIME             1106
#define IDC_IPADDRESS_LOCAL_SUBMASK     1107
#define IDC_IPADDRESS_LOCAL_GATEWAY     1108
#define IDC_EDIT_SERVER_DHCP            1109
#define IDC_IPADDRESS_SERVER_IP         1110
#define IDC_EDIT_SERVER_PORT            1111
#define IDC_IPADDRESS_LOCAL_SETIP       1112
#define IDC_EDIT_LOCAL_SETPORT          1113
#define IDC_EDIT_LOCAL_SETNAME          1114
#define IDC_EDIT_LOCAL_SETTIME          1115
#define IDC_IPADDRESS_LOCAL_SETSUBMASK  1116
#define IDC_IPADDRESS_LOCAL_SETGATEWAY  1117
#define IDC_IPADDRESS_SERVER_SETIP      1118
#define IDC_EDIT_SERVER_SETPORT         1119
#define IDC_COMBO_TWO                   1120
#define IDC_BUTTON_LOCAL_SETID          1121
#define IDC_COMBO_SETPOWER              1122
#define IDC_EDIT_SETRESPONSE            1123
#define IDC_COMBO_TAG_SETPOWER          1132
#define IDC_EDIT7                       1133
#define IDC_EDIT_LOCAL2_GETID1          1133
#define IDC_BUTTON_CONNECTDrivace       1136
#define IDC_STATIC_connect              1137
#define IDC_STATIC_connect2             1138

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
