//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Location.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LOCATION_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SETPORT              129
#define IDD_DIALOG_SETTAG               131
#define IDD_DIALOG_LISTSHOW             133
#define IDD_DIALOG_IMAGESHOW            135
#define IDD_DIALOG_SETIMAGEPORT         137
#define IDD_DIALOG_CONFIG               140
#define IDD_DIALOG_CONFIG_SERVER        141
#define IDD_DIALOG_CONFIG_MAP           142
#define IDD_DIALOG_CONFIG_DISPLAY       143
#define IDD_DIALOG_CONFIG_WARNING       144
#define IDD_DIALOG1                     145
#define IDD_DIALOG_WARNING_INFO         145
#define IDD_DIALOG_IMAGESHOW_PORTSHOW   146
#define IDD_DIALOG_TAG_ONLINE           147
#define IDD_DIALOG_OLDDATA              148
#define IDD_DIALOG_OLDDATA_TONGJI       149
#define IDD_DIALOG_OLDDATE_REPLAY       150
#define IDD_DIALOG2                     152
#define IDD_DIALOG_SETNET               152
#define IDC_TAB1                        1000
#define IDC_BUTTON_CONNECT              1001
#define IDC_BUTTON_GetID                1002
#define IDC_BUTTON_SETID                1003
#define IDC_EDIT_GETID1                 1004
#define IDC_EDIT_GETID2                 1005
#define IDC_EDIT_SETID1                 1006
#define IDC_EDIT_SETID2                 1007
#define IDC_COMBO1                      1008
#define IDC_COMBO_COM                   1008
#define IDC_COMBO_IP                    1008
#define IDC_COMBO_HOUR_START            1008
#define IDC_CHECK1                      1009
#define IDC_CHECK_ALL                   1009
#define IDC_CHECK_TAG_NOMOVE            1009
#define IDC_COMBO_HOUR_END              1009
#define IDC_CHECK_BATTERY               1009
#define IDC_CHECK_ALL2                  1010
#define IDC_BUTTON_GETSLEEPTIME         1013
#define IDC_BUTTON_SETTIME              1014
#define IDC_EDIT_GETTIME                1019
#define IDC_EDIT_SETTIME                1020
#define IDC_COMBO_COMPORT               1021
#define IDC_EDIT_GETWORKTIME            1023
#define IDC_LIST_Info                   1024
#define IDC_EDIT_SETWORKTIME            1024
#define IDC_STATIC_IP                   1025
#define IDC_BUTTON_SET                  1026
#define IDC_EDIT_ID1                    1032
#define IDC_ID2                         1033
#define IDC_BUTTON_DELETE               1034
#define IDC_BUTTON_BACK                 1036
#define IDC_BUTTON_GET_WORKTIME         1037
#define IDC_BUTTON_SET_WORKTIME         1038
#define IDC_EDIT_ServerPort             1051
#define IDC_LIST1                       1052
#define IDC_EDIT1                       1053
#define IDC_LIST3                       1053
#define IDC_LIST_OFFLINE                1053
#define IDC_BUTTON1                     1054
#define IDC_BUTTON2                     1055
#define IDC_EDIT_MAP                    1055
#define IDC_BUTTON_OPEN                 1056
#define IDC_CHECK_AUTO_Emergency        1057
#define IDC_CHECK_SHOW_PORT             1058
#define IDC_CHECK_SHOW_TIMEOUT          1059
#define IDC_EDIT_SHOW_TIME              1060
#define IDC_COMBO_SHOW_TYPE             1061
#define IDC_CHECK_SERVER_NET            1062
#define IDC_EDIT_NO_MOVE_TIME           1062
#define IDC_CHECK_TAGTIMEOUT            1063
#define IDC_CHECK_EMERGENCY             1064
#define IDC_EDIT_SERVERNET_TIME         1065
#define IDC_EDIT_WARNING_INFO           1066
#define IDC_BUTTON_WARNING_ALL          1067
#define IDC_EDIT_INFO                   1068
#define IDC_BUTTON_ClearAll             1069
#define IDC_BUTTON_CLOSE                1070
#define IDC_BUTTON3                     1071
#define IDC_LIST2                       1072
#define IDC_BUTTON4                     1073
#define IDC_EDIT2                       1074
#define IDC_BUTTON5                     1075
#define IDC_BUTTON_REFRESH              1076
#define IDC_BUTTON_ADD                  1077
#define IDC_BUTTON_DEL                  1078
#define IDC_BUTTON_SAVE                 1079
#define IDC_BUTTON_UPDATEToList         1080
#define IDC_BUTTON_Clean_List           1081
#define IDC_BUTTON_COMStart             1082
#define IDC_STATIC_Show_Tag             1083
#define IDC_BUTTON_OldData              1084
#define IDC_RADIO_AUTO                  1085
#define IDC_RADIO_HAND                  1086
#define IDC_STATIC_TITAL                1087
#define IDC_BUTTON_TAG_ONLINE           1088
#define IDC_LIST_ONLINE                 1089
#define IDC_STATIC_SETCOUNT             1090
#define IDC_STATIC_ONLINE               1091
#define IDC_STATIC_OFFLINE              1092
#define IDC_EDIT_PORT                   1093
#define IDC_BUTTON_SAVEIP               1094
#define IDC_DATETIMEPICKER_START        1096
#define IDC_COMBO_MINUTE_START          1097
#define IDC_DATETIMEPICKER_END          1098
#define IDC_COMBO_MINUTE_END            1099
#define IDC_BUTTON_START                1100
#define IDC_CHECK2                      1101
#define IDC_CHECK_TAG_CONTINU           1101
#define IDC_CHECK_TAG_CONTINUOUS        1101
#define IDC_BUTTON_SPEED_ADD            1102
#define IDC_BUTTON_SPEED_DEC            1103
#define IDC_BUTTON_PASUE                1104
#define IDC_STATIC_SPEED                1105
#define IDC_STATIC_TIME                 1106
#define IDC_EDIT_BATTERY_VALUE          1107
#define IDC_EDIT_TAG_CONTINUOUS         1109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
